import numpy as np
import matplotlib.pyplot as plt
from matplotlib import rcParams
import pandas as pd
import json
import pickle
import sys
from pathlib import Path

# ==========================================================
# 0. PATH RESOLUTION FOR PICKLE
# ==========================================================
# Plotter sits in /home/amsalda
# define_objects sits in /home/amsalda/mp_compute
current_dir = Path(__file__).resolve().parent
compute_dir = current_dir / "mp_compute"
sys.path.append(str(compute_dir))

# Now pickle will find the module and successfully unpack your arrays!
from define_objects import SteadyStateVaryVResult

# ==========================================================
# KC'S FIGURE GUIDELINES ENFORCEMENT (Strict Parameterization)
# ==========================================================
rcParams['font.family'] = 'sans-serif'
rcParams['pdf.fonttype'] = 42
rcParams['ps.fonttype'] = 42

# Global Axis and Tick Formatting (0.5 pt for boxes/axes)
rcParams['axes.linewidth'] = 0.5
rcParams['xtick.major.width'] = 0.5
rcParams['ytick.major.width'] = 0.5

# Font Sizes (Keeping KC's 20-25% larger ratio)
rcParams['axes.titlesize'] = 25
rcParams['axes.labelsize'] = 22
rcParams['xtick.labelsize'] = 20
rcParams['ytick.labelsize'] = 20
rcParams['legend.fontsize'] = 16

debug = True
def discover_latest_varyV_runs(base_dir="."):
    """
    Scans the base directory for the newest 'results_*' folders containing 'TPvaryV'.
    Separates them into forward (flip=False) and reverse (flip=True) runs.
    """
    base_path = Path(base_dir)
    fwd_folder = None
    rev_folder = None

    # Sort folders by newest modification time
    directories = sorted(
        [d for d in base_path.glob("results_*") if d.is_dir()],
        key=lambda x: x.stat().st_mtime,
        reverse=True
    )
    if debug: print(f"{len(directories)} directories found", flush=True)

    for folder in directories:
        run_name = str(folder).split("results_")[1]
        if fwd_folder is not None and rev_folder is not None:
            break

        meta_file = folder / "checkpoint_meta.json"
        init_file = folder / f"{run_name}.json"
        if not meta_file.exists():
            if debug: print(f"no meta in {folder}", flush=True)
            continue

        try:
            with open(meta_file, 'r', encoding='utf-8') as f:
                data = json.load(f)

            with open(init_file, 'r', encoding='utf-8') as q:
                init = json.load(q)

            job_name = data.get("slurm_job_name", "")
            if "TPvaryV" not in job_name:
                if debug: print(f"bad job name in {folder}", flush=True)
                continue

            # Check flip status
            if "flip" in init:
                is_flip = str(init["flip"]).strip().lower() == "true"

                if is_flip and rev_folder is None:
                    rev_folder = folder
                    print(f"--> Auto-detected Reverse Run (is_reverse=True): {folder.name}")
                elif not is_flip and fwd_folder is None:
                    fwd_folder = folder
                    print(f"--> Auto-detected Forward Run (is_reverse=False): {folder.name}")
            else:
                if debug: print(f"no is_reverse {folder}", flush=True)
        except Exception as a:
            if debug: print(f"exception {a} in processing {folder}", flush=True)
            pass

    return fwd_folder, rev_folder


def aggregate_task_data(folder_path):
    """
    Loads all varyV_raw_task*.pkl files generated by the SLURM job array,
    filters out failures, and calculates the global statistical average.
    """
    if folder_path is None:
        return None

    folder = Path(folder_path)
    pkl_files = list(folder.glob("varyV_raw_task*.pkl"))

    if not pkl_files:
        print(f"Warning: No varyV_raw_task PKL files found in {folder.name}")
        return None

    print(f"Aggregating {len(pkl_files)} array tasks from {folder.name}...")

    global_DeltaV = []
    global_I_base = []
    V_sweep = None
    successful_loops = 0
    failed_loops = 0

    for pkl_file in pkl_files:
        try:
            with open(pkl_file, 'rb') as f:
                data = pickle.load(f)

            # Assume all tasks share the exact same V_sweep macro-grid
            if V_sweep is None:
                V_sweep = data['V_sweep']

            for res in data['results']:
                # Drop unstable KMC instances
                if getattr(res, 'error_count', 0) > 10:
                    failed_loops += 1
                    continue

                # Check for NaNs safely. If the feedback loop aborted, it logged an array containing np.nan
                if np.isnan(res.DeltaV_vec).any():
                    failed_loops += 1
                    continue

                global_DeltaV.append(res.DeltaV_vec)
                global_I_base.append(res.I_baseline_vec)
                successful_loops += 1

        except Exception as e:
            print(f"Error loading {pkl_file.name}: {e}")

    print(f"Aggregation complete: {successful_loops} successful iterations, {failed_loops} dropped.")

    if successful_loops == 0:
        return None

    # Calculate global statistics
    DeltaV_matrix = np.array(global_DeltaV)
    I_base_matrix = np.array(global_I_base)

    DeltaV_avg = np.mean(DeltaV_matrix, axis=0)
    DeltaV_err = np.std(DeltaV_matrix, axis=0) / np.sqrt(successful_loops)
    I_baseline_avg = np.mean(I_base_matrix, axis=0)

    # We must recover metadata to calculate exact thermopower
    meta_file = folder / "checkpoint_meta.json"
    with open(meta_file, 'r', encoding='utf-8') as f:
        meta = json.load(f)

    repetition = meta.get("repetition", 40)
    Cg = meta.get("Cg", 2)

    # Assuming standard T0=0.001 and 7 islands
    T0 = 0.001
    T_std = repetition * T0 / 20
    dT_total = (7 - 1) * T_std

    Seebeck_coeff = DeltaV_avg / dT_total ### no minus as our deltaT is T_right-T_left
    Seebeck_err = DeltaV_err / dT_total

    df = pd.DataFrame({
        "V_baseline_(V)": V_sweep,
        "DeltaV_avg_(V)": DeltaV_avg,
        "DeltaV_err_(V)": DeltaV_err,
        "I_baseline_avg_(e/s)": I_baseline_avg,
        "Thermopower_S(V)": Seebeck_coeff,
        "Thermopower_err": Seebeck_err
    })

    # Save the aggregated CSV locally
    csv_filename = folder / f"VaryV_rep{repetition}_Global_Aggregated.csv"
    df.to_csv(csv_filename, index=False)
    print(f"Saved aggregated data to {csv_filename.name}")

    return {"df": df, "Cg": Cg, "dT": dT_total, "rep": repetition}


def plot_thermopower_varyV(fwd_folder, rev_folder, output_path):
    """
    Plots the aggregated Thermopower S(V) and Current I(V) from the varying-voltage feedback loop.
    Overlays the Forward and Reverse (flipped gradient) runs if both exist.
    """
    fwd_data = aggregate_task_data(fwd_folder)
    rev_data = aggregate_task_data(rev_folder)

    if fwd_data is None and rev_data is None:
        print("CRITICAL ERROR: No valid data found to plot. Exiting.")
        return

    # We will use the params from whichever folder exists
    base_data = fwd_data if fwd_data is not None else rev_data
    Cg = base_data["Cg"]
    dT_total = base_data["dT"]
    rep = base_data["rep"]

    fig, ax1 = plt.subplots(figsize=(10, 7))

    # --- Primary Axis: Thermopower S(V) ---
    color_s = 'tab:red'
    color_s_rev = 'darkorange'

    ax1.set_xlabel(r'Voltage Bias $V$ $\left[ \frac{e}{\langle C \rangle} \right]$', labelpad=15)
    ax1.set_ylabel(r'Thermopower $S(V)$ $\left[ \frac{k_B}{e} \right]$', color='black', labelpad=15)

    if fwd_data is not None:
        df_f = fwd_data["df"]
        line1 = ax1.errorbar(
            df_f["V_baseline_(V)"], df_f["Thermopower_S(V)"], yerr=df_f["Thermopower_err"],
            fmt='-o', color=color_s, linewidth=1.5, elinewidth=1.5, markersize=6, capsize=3,
            label=r'$S(V)$, $\Delta T>0$'
        )

    if rev_data is not None:
        df_r = rev_data["df"]
        line_r = ax1.errorbar(
            df_r["V_baseline_(V)"], df_r["Thermopower_S(V)"], yerr=df_r["Thermopower_err"],
            fmt='-s', color=color_s_rev, linewidth=1.5, elinewidth=1.5, markersize=6, capsize=3,
            label=r'$S(V)$, $\Delta T<0$'
        )

    ax1.tick_params(axis='y', length=6, width=0.5)
    ax1.tick_params(axis='x', length=6, width=0.5)

    # --- Secondary Axis: Current I(V) ---
    ax2 = ax1.twinx()
    color_i = 'tab:blue'
    color_i_rev = 'purple'
    ax2.set_ylabel(r'Current $I(V)$ $\left[ \frac{e}{\langle R \rangle \langle C \rangle} \right]$', color='black',
                   labelpad=15)

    if fwd_data is not None:
        line2, = ax2.plot(df_f["V_baseline_(V)"], df_f["I_baseline_avg_(e/s)"], '--',
                          color=color_i, linewidth=1.5, alpha=0.8, label=r'$I(V)$, $\Delta T>0$')

    if rev_data is not None:
        line2_r, = ax2.plot(df_r["V_baseline_(V)"], df_r["I_baseline_avg_(e/s)"], ':',
                            color=color_i_rev, linewidth=1.5, alpha=0.8, label=r'$I(V)$, $\Delta T<0$')

    ax2.tick_params(axis='y', length=6, width=0.5)
    for spine in ax2.spines.values():
        spine.set_linewidth(0.5)

    # --- Title and Legend ---
    Ec = 0.5/Cg
    ax1.set_title('Thermopower & Current vs. Voltage Bias\n' + rf'$|\Delta T|={dT_total/Ec:.2f}E_c$', pad=20)

    # Combine all legends logically
    lines, labels = ax1.get_legend_handles_labels()
    lines2, labels2 = ax2.get_legend_handles_labels()
    # Change 'best' to 'upper left'
    legend = ax1.legend(lines + lines2, labels + labels2,
                        loc='upper left', frameon=True, edgecolor='black')
    legend.get_frame().set_linewidth(0.5)

    fig.tight_layout()

    out_file = Path(output_path) / f"Publication_VaryV_rep{rep}_Cg{Cg}.pdf"
    plt.savefig(out_file, format='pdf', bbox_inches='tight')
    plt.close()
    print(f"Publication vector PDF saved to: {out_file.name}")


if __name__ == "__main__":
    print("Scanning directory for recent VaryV simulation runs...")

    FORWARD_RUN_DIR, REVERSE_RUN_DIR = discover_latest_varyV_runs("./")
    OUTPUT_DIRECTORY = "./"

    plot_thermopower_varyV(FORWARD_RUN_DIR, REVERSE_RUN_DIR, OUTPUT_DIRECTORY)