import os
import pandas as pd
import numpy as np
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib import rcParams
import warnings

# ==========================================
# 1. KC's Strict Formatting Guidelines
# ==========================================
rcParams['font.family'] = 'sans-serif'
rcParams['font.sans-serif'] = ['Myriad Pro', 'Arial']
rcParams['pdf.fonttype'] = 42
rcParams['ps.fonttype'] = 42

# Global Axis and Tick Formatting (0.5 pt for boxes/axes)
rcParams['axes.linewidth'] = 0.5
rcParams['xtick.major.width'] = 0.5
rcParams['ytick.major.width'] = 0.5

# Font Sizes (Keeping KC's 20-25% larger ratio)
rcParams['axes.titlesize'] = 25
rcParams['axes.labelsize'] = 22
rcParams['xtick.labelsize'] = 18
rcParams['ytick.labelsize'] = 18

# Unified Unit Strings
Volt_str = r"$\left[ \frac{e}{\langle C \rangle} \right]$"
T_str = r"$\left[ \frac{e^2}{k_B \langle C \rangle} \right]$"
S_str = r"$\left[ \frac{k_B}{e} \right]$"

# ==========================================
# 2. Configuration & Unified File Mapping
# ==========================================
FILE_NAME = 'IV_data_reintegrated_midfix.csv'
E_c = 0.025
DT_MAG = 0.02  # The absolute magnitude of the gradient
V_MAX = 2.0

# Mapping the 3 Gap Regimes to their respective columns generated by the new simulation
# Format: Plot Label -> (Base_Col, Pos_Col, Neg_Col, Color, Marker)
REGIMES = {
    r'$\Delta = 0$ (Metallic)': (
        'I_Delta_0_constant', 'I_Delta_0_grad_pos', 'I_Delta_0_grad_neg', 'tomato', 's'
    ),
    r'$\Delta = 0.2E_c$': (
        'I_Delta_0.2Ec_constant', 'I_Delta_0.2Ec_grad_pos', 'I_Delta_0.2Ec_grad_neg', 'mediumseagreen', '^'
    ),
    r'$\Delta = 2E_c$': (
        'I_Delta_2.0Ec_constant', 'I_Delta_2.0Ec_grad_pos', 'I_Delta_2.0Ec_grad_neg', 'dodgerblue', 'o'
    )
}


# ==========================================
# 3. Math Functions: Vertical Feedback Walk
# ==========================================
def walk_bidirectional_for_voltage(V_array, I_target_col, I_0, start_v_idx):
    """
    Checks the initial current state. If the gradient caused current to drop,
    walks downward (increases voltage) to restore I_0. If the gradient caused
    current to spike (e.g. gap suppression), walks upward (decreases voltage).
    """
    I_initial = I_target_col[start_v_idx]

    # If already within threshold, no bias shift is needed
    if abs(I_initial - I_0) < 1e-6:
        return 0.0

    if I_initial < I_0:
        # CASE 1: Current dropped. We need MORE voltage. (Walk down the table)
        search_I = I_target_col[start_v_idx:]
        search_V = V_array[start_v_idx:]

        cross_indices = np.where(search_I >= I_0)[0]
        if len(cross_indices) == 0:
            return np.nan

        idx_cross = cross_indices[0]
        if idx_cross == 0:
            return 0.0

        V_before, V_after = search_V[idx_cross - 1], search_V[idx_cross]
        I_before, I_after = search_I[idx_cross - 1], search_I[idx_cross]

    else:
        # CASE 2: Current spiked (Gap suppression). We need LESS voltage. (Walk up the table)
        search_I = I_target_col[:start_v_idx + 1]
        search_V = V_array[:start_v_idx + 1]

        cross_indices = np.where(search_I <= I_0)[0]
        if len(cross_indices) == 0:
            return np.nan

        idx_cross = cross_indices[-1]
        if idx_cross == len(search_I) - 1:
            return 0.0

        V_before, V_after = search_V[idx_cross], search_V[idx_cross + 1]
        I_before, I_after = search_I[idx_cross], search_I[idx_cross + 1]

    # Sub-grid linear interpolation to find the exact V where I == I_0
    if I_after == I_before:
        V_exact = V_before
    else:
        V_exact = V_before + (V_after - V_before) * ((I_0 - I_before) / (I_after - I_before))

    # delta V = V_new - V_original.
    return V_exact - V_array[start_v_idx]


# ==========================================
# 4. Data Processing & 5. Plotting
# ==========================================
def process_and_plot():
    fig1, ax1 = plt.subplots(figsize=(10, 8))  # Linear Delta V
    fig2, ax2 = plt.subplots(figsize=(10, 8))  # Linear S(V)

    # Draw the zero/baseline lines once
    ax1.axhline(0, color='black', linestyle='-', linewidth=0.8, alpha=0.3)
    ax2.axhline(0, color='black', linestyle='-', linewidth=0.8, alpha=0.8)

    print(f"Loading unified data from {FILE_NAME}...", flush=True)
    if not os.path.exists(FILE_NAME):
        print(f"Error: {FILE_NAME} not found. Please ensure it is in the same directory.")
        return

    df = pd.read_csv(FILE_NAME)
    V_array = df['Vl (V)'].values
    all_results_dfs = []

    for label, (col_base, col_pos, col_neg, color, marker) in REGIMES.items():
        if not all(col in df.columns for col in [col_base, col_pos, col_neg]):
            print(f"  [SKIP] Missing columns for {label}. Skipping.")
            continue

        print(f"  [PROCESS] Evaluating S(V) for {label}...")

        I_base = df[col_base].values
        I_pos = df[col_pos].values
        I_neg = df[col_neg].values

        results = []
        for v_idx, v_val in enumerate(V_array):
            if v_val > V_MAX: continue

            I_0 = I_base[v_idx]

            # Walk for Positive Gradient (+0.02)
            dV_pos = walk_bidirectional_for_voltage(V_array, I_pos, I_0, v_idx)
            S_pos = dV_pos / DT_MAG if not np.isnan(dV_pos) else np.nan

            # Walk for Negative Gradient (-0.02)
            dV_neg = walk_bidirectional_for_voltage(V_array, I_neg, I_0, v_idx)
            S_neg = dV_neg / (-DT_MAG) if not np.isnan(dV_neg) else np.nan

            # Average the Seebeck Coefficient to eliminate nonlinear artifacts
            with warnings.catch_warnings():
                warnings.simplefilter("ignore", category=RuntimeWarning)
                S_avg = np.nanmean([S_pos, S_neg])

            results.append({
                'Gap': label,
                'Vl': v_val,
                'I_0': I_0,
                'dV_pos': dV_pos,
                'dV_neg': dV_neg,
                'S(V)_pos': S_pos,
                'S(V)_neg': S_neg,
                'S(V)_avg': S_avg
            })

        res_df = pd.DataFrame(results)
        plot_df = res_df.dropna(subset=['S(V)_avg']).copy()
        all_results_dfs.append(plot_df)

        # GRAPH 1: Plot both positive and negative shifts
        ax1.plot(plot_df['Vl'], plot_df['dV_pos'], marker=marker, markersize=6, color='black',
                 markerfacecolor=color, linestyle='-', linewidth=1.5, alpha=0.9,
                 label=f"{label} ($\Delta T>0$)")

        ax1.plot(plot_df['Vl'], plot_df['dV_neg'], marker=marker, markersize=6, color=color,
                 markerfacecolor='white', linestyle='--', linewidth=1.5, alpha=0.9,
                 label=f"{label} ($\Delta T<0$)")

        # GRAPH 2: Plot the stabilized averaged Seebeck Coefficient
        ax2.plot(plot_df['Vl'], plot_df['S(V)_avg'], marker=marker, markersize=6, color='black',
                 markerfacecolor=color, linestyle='-', linewidth=1.5, alpha=0.9, label=label)

    if all_results_dfs:
        final_df = pd.concat(all_results_dfs, ignore_index=True)
        final_df.to_csv(f'thermopower_S_V_aggregated.csv', index=False)
        print("\nAll data exported successfully. Finalizing plots...", flush=True)

        # Finalize GRAPH 1 (Delta V)
        ax1.set_xlim(left=0, right=V_MAX)
        ax1.set_xlabel(r'Left Electrode $V_{left}$ ' + Volt_str, labelpad=15)
        ax1.set_ylabel(r'Required Bias Shift $\Delta V$ ' + Volt_str, labelpad=15)
        ax1.set_title(rf'Counteracting Bias to Maintain $I_0$ ($|\Delta T|/E_c = {round(DT_MAG / E_c, 1)}$)', pad=20)
        legend1 = ax1.legend(fontsize=15, loc='best')
        if legend1: legend1.get_frame().set_linewidth(0.5)
        ax1.grid(True, linestyle='--', linewidth=0.5, color='lightgray')

        fig1.tight_layout()
        fig1.savefig('Delta_V_vs_Voltage_Unified.pdf', format='pdf', bbox_inches='tight')
        plt.close(fig1)

        # Finalize GRAPH 2 (Seebeck S(V))
        ax2.set_xlim(left=0, right=V_MAX)
        ax2.set_xlabel(r'Left Electrode $V_{left}$ ' + Volt_str, labelpad=15)
        ax2.set_ylabel(r'Thermopower $S(V)$ ' + S_str, labelpad=15)
        ax2.set_title(rf'Thermopower vs. Voltage ($|\Delta T|/E_c = {round(DT_MAG / E_c, 1)}$)', pad=20)
        legend2 = ax2.legend(fontsize=18, loc='best')
        if legend2: legend2.get_frame().set_linewidth(0.5)
        ax2.grid(True, linestyle='--', linewidth=0.5, color='lightgray')

        fig2.tight_layout()
        fig2.savefig('Thermopower_S_vs_Voltage_Unified.pdf', format='pdf', bbox_inches='tight')
        plt.close(fig2)

        print("Success! Unified plots saved as vector PDFs.")


if __name__ == '__main__':
    process_and_plot()